apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  # If you are not familiar with YAML syntax (|)
  # Refer to https://www.w3schools.io/file/yaml-multiline-strings/#google_vignette
  
  # file-like keys
  # See mongodb configuration options:
  # https://www.mongodb.com/docs/manual/reference/configuration-options/#mongodb-setting-net.bindIpAlll
  # See how to deploy ReplicaSet in MongoDB
  # https://www.mongodb.com/docs/manual/tutorial/deploy-replica-set/
  mongodb.conf: |
    replication:
      replSetName: "rs0"
    net:
      # bindIp: localhost,<hostname(s)|ip address(es)> 
      # bindIpAll for testing purpose
      bindIpAll: true
  