####### References:
## 1. https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/
## 2. https://github.com/justmeandopensource/kubernetes/blob/master/yamls/mongodb/mongodb-statefulset.yaml
## 3. https://github.com/pelthepu/Kubernetes/blob/master/resources/statefulsets/statefulset.yaml
########

## Step 1: Create services
## Step 1.a: Headless service for stable DNS entries of StatefulSet members.
## For instances: The headless Service is named mysql, the Pods are accessible 
## by resolving <pod-name>.mongodb-svc from within any other Pod in the same Kubernetes 
## cluster and namespace.
## If need more infor about a stable network ID
## Refer to: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id
## For instance: <mongodb-sts-0>.mongodb-svc.default.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: mongodb-svc
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  clusterIP: None
  ## Pleas refer to this: https://kubernetes.io/docs/concepts/services-networking/service/#with-selectors
  selector:
    app: mongodb # Point to Pod's label, not statefulset
---
## Step 1.b: Services for reading replicas
##
##
##




