apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:  
  # Add your secret values here (base64 encoded)
  # how to convert a given string to base64 encoded string: 
  # refer to: https://www.baeldung.com/linux/cli-base64-encode-decode
  MONGODB_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGODB_INITDB_ROOT_PASSWORD: YWRtaW4=